service: icheckin

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  timeout: 900
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in the icheckin bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
          Resource:
            - 'arn:aws:s3:::icheckin-user-data/*'
  environment:
    telegram_bot_key: ${env:telegram_bot_key}
    FONTCONFIG_PATH: "/opt/etc/fonts"

functions:
  main:
    memorySize: 1000
    handler: handler.lambda_handler
    events:
      - http:
          path: icheckin
          method: any
          cors: true

    layers:
      - ${cf:lambda-layer-dev.PythonLayerExport}
      - ${cf:lambda-layer-dev.ChromedriverLayerExport}

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .vscode/**
    - venv/**
    - __pycache__/**
    - node_modules/**
    - lambda/**
    - secrets/**
    - jspm_packages/**
    - .serverless/**
    - others/**
    - chromedriver.exe
    - lambda_layers/**
    - curl_reqs.txt
    - aws.excalidraw
    - persistences
